apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: bo-yoon
    provider: github
    repository: jx3-deploy-sample01
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: bo-yoon-jx3-deploy-sample01
  namespace: jx
spec:
  httpCloneURL: https://github.com/bo-yoon/jx3-deploy-sample01.git
  org: bo-yoon
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx3-deploy-sample01
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/bo-yoon/jx3-deploy-sample01
